#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /css/**, /js/**, /images/**
      cache:
        period: 3600s

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
